AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'config/initializers/*'
    - 'config/environments/*'
    - 'bin/spring'
    - 'db/migrate/*'
    - 'test/controllers/*'
Metrics/LineLength:
  Max: 90
Metrics/MethodLength:
  CountComments: false
  Max: 12
Metrics/AbcSize:
  Max: 17
Metrics/CyclomaticComplexity:
  Max: 7
