AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'config/initializers/*'
    - 'config/environments/*'
    - 'bin/spring'
    - 'db/migrate/*'
    - 'test/controllers/*'
Metrics/LineLength:
  Max: 90
Metrics/MethodLength:
  CountComments: false
  Max: 12
